language: node_js

node_js:
  - v4

services:
  - mysql

addons:
  code_climate:

env:
  NODE_ENV: 'test'

notifications:
  email:
    - alberto@wejs.org

before_script:
  - mysql -e 'create database test;'

after_success:
- npm install coveralls
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js